[package]
name = "gpui_ce_components_webview"
description = "WebView support for GPUI, based on Wry."
keywords = ["webview", "gpui","wry"]
license.workspace = true
documentation = "https://docs.rs/gpui_ce_components_webview"
homepage.workspace = true
repository.workspace = true
readme = "README.md"
edition.workspace = true
publish = true
version.workspace = true

[features]
inspector = ["wry/devtools"]

[lib]
name = "gpui_wry"
doctest = false

[dependencies]
anyhow.workspace = true
gpui.workspace = true
wry = { version = "0.53.3", package = "lb-wry" }
