[package]
name = "gpui_ce_components_macros"
description = "Macros for GPUI Component."
version.workspace = true
license.workspace = true
publish = true
edition.workspace = true
repository.workspace = true
homepage.workspace = true

[lib]
name = "gpui_component_macros"
proc-macro = true

[lints]
workspace = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = "2.0"

[package.metadata.cargo-machete]
ignored = ["proc-macro2", "core-text"]
